### ISSUE TITLE
error :import autodrome.envs

### ISSUE THREAD

**Issue by mingkin** [vojtamolda/autodrome#5]
```python
import autodrome.envs
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/wm/anaconda3/pkgs/autodrome-master/autodrome/__init__.py", line 1, in <module>
    from .simulator import ETS2, ATS
  File "/Users/wm/anaconda3/pkgs/autodrome-master/autodrome/simulator/__init__.py", line 1, in <module>
    from .simulator import Simulator
  File "/Users/wm/anaconda3/pkgs/autodrome-master/autodrome/simulator/simulator.py", line 61
    print(f"Setting up mod with map in '{mod_dir}'...")
                                                     ^
SyntaxError: invalid syntax
```

**Comment by vojtamolda** [comment]
Hello @mingkin,

What version of Python are you using? The `print(f"Something {var}")` (aka the f-string syntax or formatted string literal) is supported since Python 3.6. Check out [PEP 498](https://docs.python.org/3/whatsnew/3.6.html#pep-498-formatted-string-literals) for more details.

I'm not actually sure if the documentation mentions the required Python version anywhere. So I apologize if you can't find it. I'll be happy to fix it.
