### ISSUE TITLE
Install error in requirements-darwin.txt (OS is Ubuntu 16.04)

### ISSUE THREAD

**Issue by aurotripathy** [vojtamolda/autodrome#6]
Thank you and hope you can answer a question.
I'm looking for a open gym env for **linux** 
Can I make this repo work under linux.
I get the following error.
```

(pyt1.0) auro@auro-ml:~/rl/autodrome$ pip install -r requirements-darwin.txt
Requirement already satisfied: pyobjc in /home/auro/anaconda3/envs/pyt1.0/lib/python3.6/site-packages/pyobjc-5.1.2-py3.6.egg (from -r requirements-darwin.txt (line 1)) (5.1.2)
Collecting pyobjc-framework-Cocoa (from -r requirements-darwin.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/fe/e9/ba571f1415cfa7281ee1d6a44573ae5f1d0c5216a869bfaae7f30172d3e3/pyobjc-framework-Cocoa-5.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-4hnja3o5/pyobjc-framework-Cocoa/setup.py", line 24, in <module>
        extra_link_args=['-framework', 'CoreFoundation']),
      File "/tmp/pip-install-4hnja3o5/pyobjc-framework-Cocoa/pyobjc_setup.py", line 389, in Extension
        os_level = get_os_level()
      File "/tmp/pip-install-4hnja3o5/pyobjc-framework-Cocoa/pyobjc_setup.py", line 203, in get_os_level
        pl = plistlib.readPlist('/System/Library/CoreServices/SystemVersion.plist')
      File "/home/auro/anaconda3/envs/pyt1.0/lib/python3.6/plistlib.py", line 162, in readPlist
        with _maybe_open(pathOrFile, 'rb') as fp:
      File "/home/auro/anaconda3/envs/pyt1.0/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/home/auro/anaconda3/envs/pyt1.0/lib/python3.6/plistlib.py", line 120, in _maybe_open
        with open(pathOrFile, mode) as fp:
    FileNotFoundError: [Errno 2] No such file or directory: '/System/Library/CoreServices/SystemVersion.plist'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-4hnja3o5/pyobjc-framework-Cocoa/

```

**Comment by vojtamolda** [comment]
Hello @aurotripathy,

I'm sorry that I have to disappoint you but unfortunately Linux is not supported at the moment. The project currently works only under macOS. The specific error you are seeing is caused by a lack of objective C Python bindings for Linux. It's a macOS specific feature.

There's already an opened issue for Linux support here - #1. There's no serious technical problem. It just requires some development time.
